Format data
SW8-Mobility/speed_limit_floating_car_data pull request #19
Opened 2023-03-28 12:29 UTC by JakobFaarGreg

2023-03-28 12:29 UTC, JakobFaarGreg commented
#15

2023-04-03 06:48 UTC, frejaz commented on pipeline/preprocessing/format_data.py
> +    """Appends to coordinate from a trip to the correct segment in segment_dict
```suggestion
    """Appends coordinates from a trip to the correct segment in segment_dict
```

2023-04-03 06:49 UTC, frejaz commented on pipeline/preprocessing/format_data.py
> +        key, coordinates = mapped_cords
// Key is the osm_id

2023-04-03 07:23 UTC, frejaz commented on pipeline/preprocessing/format_data.py
> +def map_segments_to_coordinates(
Jeg går ud fra at det her er fra en single trip - måske lige skriv at dataformatet er således, at vi går ud fra at der er lige mange osm_id'er og coordinates. Ellers kune jeg forestille mig at det kunne være at det kunne være lidt svært at forstå

2023-04-03 07:30 UTC, frejaz commented on pipeline/preprocessing/format_data.py
> +    df["osm_id"] = combined_col.apply(  # split apart the osm_ids
Jeg er ikke sikker på hvad det betyder

2023-04-03 07:32 UTC, anesheim-uni requested changes

2023-04-03 07:32 UTC, anesheim-uni commented on pipeline/preprocessing/format_data.py
> +segment_to_coordinates_list = list[tuple[int, list]]
På linje 19-21 er der andre typealiases, og de er med PascalCase.
Jeg synes de skal placeres sammen, og som minimum have samme casing.

2023-04-03 07:32 UTC, anesheim-uni commented on pipeline/preprocessing/format_data.py
> +        return []
What. Burde vi ikke throw en error?

2023-04-03 07:32 UTC, anesheim-uni commented on pipeline/preprocessing/format_data.py
> +    mapped_df.to_csv("test.csv", index=False)
Hmm, skal vel ikke med ind på main. 
Måske udkommenteres eller placeres i readme?

2023-04-03 07:33 UTC, frejaz commented on pipeline/preprocessing/format_data.py
> +        segment_to_coordinates_list: list of tuples with a segment, and it's coordinates
```suggestion
        segment_to_coordinates_list: list of tuples with a segment (osm_id), and it's coordinates as a list
```

2023-04-03 07:34 UTC, frejaz requested changes
Small comments

2023-04-04 06:48 UTC, frejaz approved these changes
Good fix <3

2023-04-04 06:52 UTC, anesheim-uni approved these changes

2023-04-04 06:53 UTC, merged