Compute features
SW8-Mobility/speed_limit_floating_car_data pull request #36
Opened 2023-04-05 09:42 UTC by AlexanderHHansen

Created files to add features to our dataframe. We compute features like min, max, median, mean for each trip for a segment and also aggregates for each of them.

2023-04-05 11:11 UTC, JakobFaarGreg requested changes

2023-04-05 11:11 UTC, JakobFaarGreg commented on tests/preprocessing/compute_features/test_compute_features.py
> +# TODO: check where none/empty lists in coloumns should be handled
Er det her ikke prioriteret for denne pull request?

2023-04-11 10:47 UTC, anesheim-uni commented on archive/analysis_metrics.py
> +    # calculate_distance_and_speed(filtered_df)
Remove if not needed.

2023-04-11 10:48 UTC, anesheim-uni commented on pipeline/preprocessing/compute_features/calculate_speeds_distances.py
> +sys.path.append(parentdir)
Er dette nødvendigt nu når vi har fixed imports?

2023-04-11 10:51 UTC, anesheim-uni commented on pipeline/preprocessing/compute_features/calculate_speeds_distances.py
> +    uses formula for euclidian distance, which is not 100% accurate?
"Which is not 100 accurate?" skal vel ikke med?

2023-04-11 11:06 UTC, anesheim-uni commented on pipeline/preprocessing/compute_features/type_alias.py
> +FeatureCalculator = Callable[[pd.DataFrame], Any]
Disse kunne godt bruges flere steder i compute_features.

2023-04-11 11:07 UTC, AlexanderHHansen commented on pipeline/preprocessing/compute_features/compute_features.py
> +        aggregate_func: the function to a
rettet

2023-04-11 11:10 UTC, AlexanderHHansen commented on archive/analysis_metrics.py
> +    # calculate_distance_and_speed(filtered_df)
har ikke noget med pr at gøre

2023-04-11 11:10 UTC, anesheim-uni commented on tests/preprocessing/compute_features/test_calculate_speeds_distances.py
> +sys.path.append(parentdir)
Er det ikke unødvendigt jf. import PR?

2023-04-11 11:12 UTC, anesheim-uni reviewed
Minor details/changes, pretty good overall

2023-04-11 11:13 UTC, AlexanderHHansen commented on tests/preprocessing/compute_features/test_calculate_speeds_distances.py
> +sys.path.append(parentdir)
Ting failer hvis det ikke er med. Bliver dermed fixet i imports pr.

2023-04-11 11:28 UTC, anesheim-uni approved these changes
All good

2023-04-11 11:36 UTC, JakobFaarGreg approved these changes
lgtm

2023-04-11 11:36 UTC, merged