Models
SW8-Mobility/speed_limit_floating_car_data pull request #47
Opened 2023-04-13 11:21 UTC by AlexanderHHansen

Made the code to create different models. For the regression model, a "snap to closest speed limit" function has been implemented to be used for those. Functionality for scoring our models is implemented. I used metrics typically used in regression models, as I think those metrics are more appropriate than those for classification. Much of the code is not really typed, because it wraps code from sklearn, which does not support type hints...

2023-04-13 21:14 UTC, anesheim-uni commented on pipeline/models/models.py
> +    return StatisticalModel()
Does this work?

2023-04-13 21:18 UTC, anesheim-uni approved these changes
Virkelig godt arbejde!

2023-04-14 07:26 UTC, JakobFaarGreg requested changes

2023-04-14 07:26 UTC, JakobFaarGreg commented on pipeline/models/utils/scoring.py
> +    after = SPEED_LIMITS[pos]
```suggestion
    index = bisect_left(SPEED_LIMITS, speed)
    if index == 0:
        return SPEED_LIMITS[0]
    if index == len(SPEED_LIMITS):
        return SPEED_LIMITS[-1]
    before = SPEED_LIMITS[index - 1]
    after = SPEED_LIMITS[index]
```

2023-04-14 07:26 UTC, JakobFaarGreg commented on tests/models/scoring/test_scoring.py
> +
```suggestion
```

2023-04-14 07:26 UTC, JakobFaarGreg commented on pipeline/models/utils/scoring.py
> +    If two numbers are equally close, return the smallest number.
Tilføj grunden dertil, det føles arbitrært som det er skrevet nu. 
Men det er grundlæggende fordi det er sikkerhedsmæssigt bedre at køre langsommere og man kommer ikke i bødeproblemer ift. at køre for stærkt

2023-04-14 09:56 UTC, JakobFaarGreg approved these changes

2023-04-14 09:56 UTC, merged