Added skeleton files
SW8-Mobility/speed_limit_floating_car_data pull request #53
Opened 2023-04-14 09:43 UTC by anesheim-uni

2023-04-28 12:52 UTC, JakobFaarGreg requested changes

2023-04-28 12:52 UTC, JakobFaarGreg commented on pipeline/models/models.py
> +    # )
delete?

2023-04-28 12:52 UTC, JakobFaarGreg commented on pipeline/preprocessing/compute_features/feature.py
> +    Basicly wraps a list of features.
```suggestion
    Basically wraps a list of features.
```

2023-04-28 12:52 UTC, JakobFaarGreg commented on pipeline/preprocessing/sk_formatter.py
> +        # self.__encode_target()
Burde det være en mere sigende kommentar?

2023-04-28 12:52 UTC, JakobFaarGreg commented on pipeline/preprocessing/sk_formatter.py
> +        # return train_test_split(x, y, test_size=self.test_size, random_state=42)
delete?

2023-04-28 12:52 UTC, JakobFaarGreg commented on pipeline/run_models.py
> +) -> dict[Model, Any]:  # TODO: update docstring
Er den her todo igang?

2023-04-30 11:14 UTC, anesheim-uni commented on pipeline/models/models.py
>      )
Tidligere var `n_jobs = CORE_NUM`, men det bruger vi ikke længere?

2023-04-30 11:15 UTC, anesheim-uni commented on pipeline/models/statistical_model.py
>              list: list of predictions.
return type ikke korrekt i docstring

2023-04-30 11:17 UTC, anesheim-uni commented on pipeline/models/utils/scoring.py
>      Args:
docstring og parameters matcher ikke. pd.DataFrame vs np.ndarray

2023-04-30 11:18 UTC, anesheim-uni commented on pipeline/models/utils/scoring.py
>      Args:
docstring og parameters matcher ikke. pd.DataFrame vs np.ndarray

2023-04-30 11:19 UTC, anesheim-uni commented on pipeline/preprocessing/sk_formatter.py
> +            target (Feature, optional): The future to be used as target. Defaults to None.
```suggestion
            target (Feature, optional): The feature to be used as target. Defaults to None.
```

2023-04-30 11:20 UTC, anesheim-uni commented on pipeline/preprocessing/sk_formatter.py
> +            discard_features (FeatureList, optional): _description_. Defaults to None.
```suggestion
            discard_features (FeatureList, optional): Optional list of features to discard. Defaults to None.
```

2023-04-30 11:23 UTC, anesheim-uni commented on pipeline/run_models.py
> +# Model = dict[str, Model]
```suggestion

```

2023-04-30 11:27 UTC, anesheim-uni commented on pipeline/run_models.py
> +    Returns: dictionary of model name to trained model model
```suggestion
    Returns: 
          dict[Model, Any]:     dictionary of model name to trained model
```

2023-04-30 11:27 UTC, anesheim-uni commented on pipeline/run_models.py
> +    """
Mærkelig docstring format

2023-04-30 11:28 UTC, anesheim-uni commented on pipeline/run_models.py
> +    """
Missing return type in docstring:
```suggestion
       dict[str, dict]: Returns dictionary of scoring metrics for each model.
    """
```

2023-04-30 11:29 UTC, anesheim-uni commented on pipeline/run_models.py
> +    """
Anderledes docstring format end normalt

2023-04-30 11:29 UTC, anesheim-uni reviewed
Comment + changes. 
Husk at læg mærke til der er forslag til ændringer, da bare kan commites direkte.

2023-05-01 06:44 UTC, CasperKjaerhus commented on pipeline/preprocessing/compute_features/feature.py
> +    Basicly wraps a list of features.
```suggestion
    Wraps a list of features.
```

2023-05-01 06:45 UTC, AlexanderHHansen commented on pipeline/models/models.py
>      )
Det skal stadig med, fix

2023-05-01 06:51 UTC, AlexanderHHansen commented on pipeline/preprocessing/sk_formatter.py
> +        # self.__encode_target()
target bliver gemt i y og bliver fjernet fra df. Der sker ikke andet.

2023-05-01 06:56 UTC, AlexanderHHansen commented on pipeline/run_models.py
> +    """
yep

2023-05-01 07:29 UTC, frejaz approved these changes
noice

2023-05-03 12:31 UTC, JakobFaarGreg approved these changes

2023-05-03 12:31 UTC, CasperKjaerhus commented on pipeline/models/models.py
> +CORE_NUM = 15  # how many cores to use in grid_search
Man kan bruge
```python
import multiprocessing

multiprocessing.cpu_count()
```

til at finde hvor mange cores der er.

2023-05-03 12:41 UTC, CasperKjaerhus requested changes
Der mangler docstrings og kommentarer på rigtig mange funktioner

2023-05-03 12:49 UTC, CasperKjaerhus commented on pipeline/preprocessing/sk_formatter.py
> +        self.params = self.__params()
kommentarer

2023-05-03 12:59 UTC, CasperKjaerhus commented on pipeline/models/models.py
>      }
kommentar til hvad parameters betyder

2023-05-05 06:43 UTC, CasperKjaerhus approved these changes

2023-05-05 06:43 UTC, merged