Data exploration of ground truth
SW8-Mobility/speed_limit_floating_car_data pull request #99
Opened 2023-05-16 07:26 UTC by CasperKjaerhus

2023-05-16 07:33 UTC, frejaz commented on data_exploration/road_type_distribution.py
> +share_files = "/share-files/raw_data_pkl/"
Add docstrings

2023-05-16 07:34 UTC, frejaz commented on data_exploration/road_type_distribution.py
> +    road_amount_df = df[Feature.VEJTYPESKILTET.value].value_counts()
Er der en grund til at du har slettet det som er under det her? Vi vil vel gerne have den total procent(?)

2023-05-16 07:35 UTC, frejaz commented on data_exploration/ground_truth_speed_limit_distribution.py
> +share_files = "/share-files/raw_data_pkl/"
Add docstrings

2023-05-16 07:35 UTC, frejaz reviewed
Add some comments

2023-05-16 07:37 UTC, CasperKjaerhus commented on data_exploration/road_type_distribution.py
> +    road_amount_df = df[Feature.VEJTYPESKILTET.value].value_counts()
Den er i total procent.

2023-05-16 07:38 UTC, CasperKjaerhus commented on data_exploration/road_type_distribution.py
> +share_files = "/share-files/raw_data_pkl/"
👀

2023-05-16 07:38 UTC, CasperKjaerhus commented on data_exploration/ground_truth_speed_limit_distribution.py
> +share_files = "/share-files/raw_data_pkl/"
👀

2023-05-16 07:58 UTC, frejaz approved these changes
finno

2023-05-16 08:14 UTC, AlexanderHHansen commented on data_exploration/road_type_distribution.py
> +""" This script calculates the distribution of roat types in the ground truth dataset.
```suggestion
""" This script calculates the distribution of road types in our dataset.
```

2023-05-16 08:15 UTC, AlexanderHHansen commented on pipeline/preprocessing/compute_features/feature.py
> +    VEJTYPESKILTET = "VEJTYPESKILTET"
hvorfor er nogen kaps og andre ikke?

2023-05-16 08:16 UTC, AlexanderHHansen requested changes
en typo + noget småt

2023-05-16 08:21 UTC, CasperKjaerhus commented on pipeline/preprocessing/compute_features/feature.py
> +    VEJTYPESKILTET = "VEJTYPESKILTET"
Alle burde være caps, siden vi ikke .lower nogle under merge af ground truth

2023-05-16 08:21 UTC, CasperKjaerhus commented on pipeline/preprocessing/compute_features/feature.py
> +    VEJTYPESKILTET = "VEJTYPESKILTET"
Men vi anvender ingen af de andre på noget tidspunkt

2023-05-17 08:22 UTC, AlexanderHHansen approved these changes

2023-05-17 08:22 UTC, merged